name:                win32-named-pipes
version:             0.1.0.0
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"

library:
  source-dirs:         lib
  ghc-options:
  - -Wall
  - -Wdeprecations
  - -threaded
  dependencies:
  - base
  - bytestring
  - data-default
  - transformers
  - Win32 >= 2.5.1.0

executables:
  test-exe:
    source-dirs:  app
    main:         Main.hs
    ghc-options:
    - -Wall -Wdeprecations
    - -threaded
    - +RTS -N -RTS
    dependencies:
    - base
    - bytestring
    - data-default
    - win32-named-pipes
    - Win32
